hired/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  resources :sessions, only:[:new, :create, :destroy]
  resources :users
  get "*path" => redirect("/")
end

hired/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hired/app/models/session.rb
# == Schema Information
#
# Table name: sessions
#
#  id            :integer          not null, primary key
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  session_token :integer          default(0), not null
#  user_id       :integer          default(0), not null
#

class Session < ApplicationRecord
  after_initialize :ensure_session_token
  validates :user_id, presence: true
  validates :session_token, uniqueness: true

  belongs_to :user,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64( 16 )
  end
  def remove_session_token
    self.session_token = nil
  end
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64( 16 )
  end
  
  def self.get_user_id_by_token( st )
    session = Session.find_by( session_token:st )
    session.user_id unless session.nil?
  end
  def self.sign_out_user( user_id )
    sessions = Session.where( user_id: user_id )
    sessions.each do |s|
      s.destroy
    end
  end

end

hired/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  username        :string           default(""), not null
#  password_digest :string           default(""), not null
#

class User < ApplicationRecord
  attr_reader :password

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, allow_nil: true, length:{ minimum: 6 }

  has_many :sessions,
    primary_key: :id, 
    foreign_key: :user_id,
    class_name: :Session
 
  def password=( pass )
    @password = pass
    self.password_digest = BCrypt::Password.create( pass )
  end

  def is_password?( pass )
    BCrypt::Password.new( self.password_digest ).is_password?( pass )
  end

  def self.find_by_credentials( uname, pass )
    user = User.find_by( username: uname )
    return nil if user.nil?
    return user if user.is_password?( pass )
    return nil
  end
end

hired/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def login!( user )
    s = Session.new( user_id: user.id )
    s.save
    session[:session_token] = s.session_token
  end
  def logout!
    Session.sign_out_user( current_user.id )
    session[:session_token] = nil
  end

  def current_user
    id = Session.get_user_id_by_token( session[:session_token] )
    User.find(id) unless id.nil?
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in!
    redirect_to new_session_url unless logged_in?
  end

end

hired/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 # before_action :set_session, only: [:show, :new, :edit, :update, :destroy]

  # GET /sessions/1
  # GET /sessions/1.json
  def new 
    if logged_in?
      redirect_to user_path( current_user )
    end
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @user = User.find_by_credentials( session_params[:username],
                                      session_params[:password] )
    unless @user.nil?
      login!( @user )
      redirect_to user_path( @user )
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    logout!
    redirect_to :new_session
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def session_params
      params.require( :user ).permit( :username, :password )
    end
end

hired/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find( params[:id] )
    redirect_to user_path( current_user ) unless current_user == @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new( user_params )

    if @user.save 
      login!( @user )
      redirect_to user_path( @user )
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require( :user ).permit( :username, :password )
    end
end

hired/app/helpers/application_helper.rb
module ApplicationHelper
end

hired/app/helpers/sessions_helper.rb
module SessionsHelper
end

hired/app/helpers/users_helper.rb
module UsersHelper
end

hired/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hired</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="full-content">

      <header>
        <%= render 'shared/header' %> 
      </header>

      <div id="content">
        <%= yield %>
      </div>

      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

hired/app/views/shared/_auth.html.erb
<input type="hidden" name="authenticity_token" value="<%form_authenticity_token %>" >

hired/app/views/shared/_errors.html.erb
<div class="errors">
  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do | error | %>
        <li class="flash-slow"> <%= error %> </li>
      <% end %>
    </ul>
  <% end %>
</div>

hired/app/views/shared/_footer.html.erb
<footer class="bg-magenta p-4">
  <div class="container">
    <ul id="footer-list">
      <li class="mt-2"><h3 class="font-weight-bold">Like what you see?</h3></li>  
      <li class="mt-2 font-weight-bold">Then give us a call and we'll chat through what you need. We've got tea, coffee and biscuits!</li>  
      <li class="mt-2 mb-1 "><a href="#">(if you're quick)</a></li>  
      <hr>
      <li class="mt-2 "><p class="font-weight-bold">(619)786-0010</p></li>  
      <li class="mt-2 "><p class="font-weight-bold">capodaca@nearshoretechnology.com</p></li>  
      <li class="mt-2 "><p class="font-weight-bold">Christopher Apodaca, Web Developer</p></li>  
      <li class="mt-2 "><p class="font-weight-bold">1353 Riverstone Parkway<br>Ste. 120-335, Canton GA 30114</p></li>  
    </ul>
    <%= render 'shared/social_links' %>
  </div>
</footer>

hired/app/views/shared/_general_header.html.erb
<nav id="general-header" class="navbar navbar-expand-lg navbar-dark bg-magenta">
  <a class="navbar-brand" href="#">Hired</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse"  >
    <ul id="lh-links" class="header-links navbar-nav">
      <li><%= link_to "Login", new_session_url, class: "nav-link" %></li>  
      <li><%= link_to "Sign Up", new_user_url, class: "nav-link"  %></li>  
    </ul>
  </div>
</nav>

hired/app/views/shared/_header.html.erb
<% if logged_in? %>
  <%= render 'shared/logged_header' %>
<% else %>
  <%= render 'shared/general_header' %>
<% end %>

hired/app/views/shared/_logged_header.html.erb
<nav id="logged-header" class="navbar navbar-expand-lg navbar-dark bg-magenta">
<a class="navbar-brand" href="#">Hired</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse">
    <ul id="lh-links" class="header-links navbar-nav">
      <li class="nav-item"><%= link_to "Home", user_url( current_user ), class: "nav-link" %></li>
      <li><%= link_to "Logout", session_url, method: :delete, class: "nav-link" %></li>  
    </ul>
  </div>
</nav>

hired/app/views/shared/_social_links.html.erb
<div class="social-icon-list">
  <!--Facebook-->
  <a class="fb-ic" role="button"><i class="fa fa-lg fa-facebook-f"></i></a>
  <!--Youtube-->
  <a class="yt-ic" role="button"><i class="fa fa-lg fa-youtube"></i></a>
  <!--Github-->
  <a class="git-ic" role="button"><i class="fa fa-lg fa-github"></i></a>
</div>

hired/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hired/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

hired/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

hired/app/views/users/new.html.erb
<div id="login-content" class="inner-content">
  <div class="container pt-5 form-container">

    <div class="form-back p-4 container">
      <h2 class="text-center gray-txt">Create Account</h2>

      <div id="create-accnt" class="form-wrap jumbotron">
        <form action="<%= users_path %>" method="post" >
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

          <input type="hidden" name="_method" value="post">
          <%= render 'shared/errors' %>

          <div class="form-group">
            <label for="login-form-username">Username</label>
            <input class="form-control" placeholder="Enter username" type="text" 
              id="login-form-username" name="user[username]" value"" />
          </div>

          <div class="form-group">
            <label for="login-form-password">Password</label>
            <input class="form-control" placeholder="Password" type="password" 
              id="login-form-password" name="user[password]" value"" />
          </div>

          <button class="btn btn-primary" type="submit" value="login">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

hired/app/views/users/show.html.erb
<div id="user-content" class="inner-content p-1">
  <ul>
    <li class="white-txt">Welcome, <%= @user.username %></li>
  </ul>
</div>


<div id="nst-store" class="p-3">
  <div id="store-header">
    <h3 class="text-center">Current Store Items</h3>
    <img id="store-logo" class="clearfix logo-img pr-3" src="/assets/bg/logo.svg" />
  </div>
  <hr>
  <div id="collection-component-1565893802445">&nbsp;</div>
</div>

<script type="text/javascript">
/*<![CDATA[*/
(function ($) {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }

  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  
  function round( value, precision ){
    var multiplier = Math.pow( 10, precision || 0 );
    return Math.round( value * multiplier ) / multiplier;
  }

  function addCurrencySpecsItem(elem){
    var mxn_rate = null;
    var target = elem;
    $.getJSON( 'https://api.exchangeratesapi.io/latest?symbols=USD,MXN&base=USD', function( data ){
      mxn_rate = data.rates.MXN;
      mxn_rate = round( mxn_rate, 3 ).toFixed(2);
    }).then(function(rate){
        var usd_price = $(target).text().split(' ')[1].split("$")[1];
        var mxn_price = ( usd_price * mxn_rate ).toFixed(2);
        var text = $(target).text();

        if( mxn_price !== null ){
          $(target).text(text + ' (MXN $' + mxn_price + ')' ); 
        }
    });
  }

  function addCurrencySpecs(){
   $('.shopify-buy__product__actual-price').each( function( i, e ){
     addCurrencySpecsItem( e );
    });
  }

  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'nearshore-shop.myshopify.com',
      storefrontAccessToken: '8699c2da26d91e94b6b15d1be937cea5',
    });

    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('collection', {
        id: '138392797237',
        node: document.getElementById('collection-component-1565893802445'),
        moneyFormat: 'USD %24%7B%7Bamount%7D%7D',
        options: {
          "product": {
            "styles": {
              "product": {
                "@media (min-width: 601px)": {
                  "max-width": "calc(25% - 20px)",
                  "margin-left": "20px",
                  "margin-bottom": "50px"
                },
                "img": {
                  "height": "calc(100% - 15px)",
                  "position": "absolute",
                  "left": "0",
                  "right": "0",
                  "top": "0"
                },
                "imgWrapper": {
                  "padding-top": "calc(75% + 15px)",
                  "position": "relative",
                  "height": "0"
                }
              },
              "button": {
                "font-weight": "bold",
                ":hover": {
                  "background-color": "#e69e38"
                },
                "background-color": "#ffaf3e",
                ":focus": {
                  "background-color": "#e69e38"
                }
              }
            },
            "text": {
              "button": "Add to cart"
            }
          },
          "productSet":{
            "iframe":false,
          },
          "productSets": {
            "iframe": false,
            "styles": {
              "products": {
                "@media (min-width: 601px)": {
                  "margin-left": "-20px"
                }
              }
            }
          },
          "modalProduct": {
            "contents": {
              "img": false,
              "imgWithCarousel": true,
              "button": false,
              "buttonWithQuantity": true
            },
            "styles": {
              "product": {
                "@media (min-width: 601px)": {
                  "max-width": "100%",
                  "margin-left": "0px",
                  "margin-bottom": "0px"
                }
              },
              "button": {
                "font-weight": "bold",
                ":hover": {
                  "background-color": "#e69e38"
                },
                "background-color": "#ffaf3e",
                ":focus": {
                  "background-color": "#e69e38"
                }
              }
            },
            "text": {
              "button": "Add to cart"
            }
          },
          "cart": {
            "styles": {
              "button": {
                "font-weight": "bold",
                ":hover": {
                  "background-color": "#e69e38"
                },
                "background-color": "#ffaf3e",
                ":focus": {
                  "background-color": "#e69e38"
                }
              }
            },
            "text": {
              "total": "Subtotal",
              "button": "Checkout"
            }
          },
          "toggle": {
            "styles": {
              "button": {
                "font-weight": "bold"
              },
              "toggle": {
                "background-color": "#ffaf3e",
                ":hover": {
                  "background-color": "#e69e38"
                },
                ":focus": {
                  "background-color": "#e69e38"
                }
              }
            }
          }
        },
      }).then(  function(){  
        addCurrencySpecs();
        }).then( function(){
          $('.shopify-buy__option-select__select').change( function(e){ 
            var price =  $($($($(e.target).parent()[0]).parent()[0]).parent()[0]).siblings('.shopify-buy__product__price').find('.shopify-buy__product__actual-price')[0];
            addCurrencySpecsItem( $(price) );
          }); 
      });
    });
  }
})(jQuery);
/*]]>*/
</script>